version: '3'

services:
  backend:
    build: .
    container_name: backend
    volumes:
      - ./backend:/app
    env_file:
      .env
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: db
    env_file:
      .env
    volumes: 
      - ./postgresql/data:/var/lib/postgresql/data

  web_server:
    image: nginx:1.19.2
    container_name: web_server
    volumes:
      - ./backend/static:/data/static
      - ./nginx/nginx.conf:/etc/nginx.conf
      - ./nginx/configs:/etc/nginx/conf.d
    depends_on:
      - backend
    ports:
      - 80:80
