# Generated by Django 3.2 on 2022-04-23 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20220407_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personfilmwork',
            name='role',
            field=models.CharField(choices=[('actor', 'Actor'), ('writer', 'Writer'), ('director', 'Director')], max_length=255, verbose_name='role'),
        ),
    ]
